* TABLE 1;
* Import data set'2023 NHIS';
PROC IMPORT datafile='C:\Users\yue_yan1\Desktop\adult23.csv'
RUN;
PROC CONTENTS data=adult23;
RUN;
** 29,522 obs and 647 variables;
LIBNAME Final 'C:\Users\yue_yan1\Desktop\Final';
DATA final.adult23;
SET work.adult23;
RUN;
PROC FREQ data=adult23;
TITLE 'Frequencies on Independent and Dependent Variables';
RUN;
PROC FREQ data=adult23;
TITLE 'Frequencies on Covariates';
RUN;
title;
DATA final (KEEP=PPSU PSTRAT WTFA_A DISAB3_A VISIONDF_A HEARINGDF_A EMPWRKFT1_A EMPWKHRS3_A EMPLSTWOR1_A EMPWHYNOT_A AGEP_A SEX_A EDUCP_A HISPALLP_A REGION);
SET adult23;
RUN;
** 29,522 obs and 15 variables;
DATA final.final;
SET work.final;
RUN;
* Narrow the age group;
DATA final_age;
SET final;
RUN;
PROC PRINT data=final_age (obs=15);
RUN;
PROC CONTENTS data=final_age;
TITLE 'Adults aged 18-64 years (working-age population)';
RUN;
** 19,781 obs and 15 variables;
title;
DATA final.final_age;
SET work.final_age;
RUN;
DATA final_variables;
SET final_age;
IF EMPWRKFT1_A IN (1,2,7,8,9) THEN Employed = 1;
ELSE Employed = 0;
IF 0 < EMPWKHRS3_A <= 20 THEN Workload = 1;
IF 20 < EMPWKHRS3_A <= 40 THEN Workload = 2;
IF 40 < EMPWKHRS3_A <= 60 THEN Workload = 3;
IF 60 < EMPWKHRS3_A <= 80 THEN Workload = 4;
IF 80 < EMPWKHRS3_A <= 95 THEN Workload = 5;
IF EMPWKHRS3_A in (97,98,99) THEN Workload = .;
IF EMPLSTWOR1_A = 1 AND EMPWHYNOT_A ~= 3 THEN Unemployed_time =1;
IF EMPLSTWOR1_A = 2 AND EMPWHYNOT_A ~= 3 THEN Unemployed_time =2;
IF EMPLSTWOR1_A = 3 AND EMPWHYNOT_A ~= 3 THEN Unemployed_time = 3;
IF EMPLSTWOR1_A = 4 AND EMPWHYNOT_A ~= 3 THEN Unemployed_time = 4;
IF EMPLSTWOR1_A in (7,8,9) AND EMPWHYNOT_A ~= 3 THEN Unemployed_time = .;
IF EMPWHYNOT_A = 3 THEN Unemployed_time = 5;
IF SEX_A = 1 THEN Sex = 1;
IF SEX_A = 2 THEN Sex = 2;
IF SEX_A in (7,9) THEN Sex = .;
IF HISPALLP_A = 1 THEN Ethnicity = 1;
IF HISPALLP_A = 2 THEN Ethnicity = 2;
IF HISPALLP_A = 3 THEN Ethnicity = 3;
IF HISPALLP_A = 4 THEN Ethnicity = 4;
IF HISPALLP_A = 5 THEN Ethnicity = 5;
IF HISPALLP_A in (6,7) THEN Ethnicity = .;
IF EDUCP_A in (1,2,3) THEN Education = 1;
IF EDUCP_A = 4 THEN Education = 2;
IF EDUCP_A = 5 THEN Education = 3;
IF EDUCP_A in (6,7) THEN Education = 4;
IF EDUCP_A = 8 THEN Education = 5;
IF EDUCP_A in (9,10) THEN Education = 6;
IF EDUCP_A in (97,99) THEN Education = .;
IF REGION = 1 THEN Region_US = 1;
IF REGION = 2 THEN Region_US = 2;
IF REGION = 3 THEN Region_US = 3;
IF REGION = 4 THEN Region_US = 4;
IF DISAB3_A = 1 THEN Disabilities = 1;
IF DISAB3_A = 2 THEN Disabilities = 0;
IF DISAB3_A = 9 THEN Disabilities = .;
IF VISIONDF_A = 1 THEN Vision = 1;
IF VISIONDF_A = 2 THEN Vision = 2;
IF VISIONDF_A = 3 THEN Vision = 3;
IF VISIONDF_A = 4 THEN Vision = 4;
IF VISIONDF_A in (7,9) THEN Vision = .;
IF HEARINGDF_A = 1 THEN Hearing = 1;
IF HEARINGDF_A = 2 THEN Hearing = 2;
IF HEARINGDF_A = 3 THEN Hearing = 3;
IF HEARINGDF_A = 4 THEN Hearing = 4;
IF HEARINGDF_A in (7,9) THEN Hearing = .;
RUN;
PROC CONTENTS data=final_variables;
RUN;
** 19,781 obs and 25 variables;
PROC FORMAT;
VALUE Employed 1= 'yes'
VALUE Workload 1= 'Part-time or minimal work'
VALUE Unemployed_time 1= 'Within the past 12 months'
VALUE Sex 1= 'Male'
VALUE Ethnicity 1= 'Hispanic'
VALUE Education 1= 'Less than high school'
VALUE Region_US 1= 'Northeast'
VALUE Disabilities 1= 'Yes'
VALUE Vision 1= 'No difficulty'
VALUE Hearing 1= 'No difficulty'
RUN;
PROC PRINT data=final_variables (obs=5);
FORMAT Employed Employed. Workload Workload. Unemployed_time Unemployed_time. Sex Sex. Ethnicity Ethnicity. Education Education. Region_US Region_US. Disabilities Disabilities. Vision Vision. Hearing Hearing.;
TITLE 'Study Populations';
RUN;
title;
PROC CONTENTS data=final_variables;
RUN;
** 19,781 obs and 25 variables;
DATA final.final_variables;
SET work.final_variables;
RUN;
PROC MEANS data=final_variables;
TITLE 'Unweighted Age';
RUN;
PROC SURVEYMEANS data=final_variables;
TITLE 'Weighted Age';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Employment Status';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Employment Status';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Working Hours (workload)';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Working Hours (workload)';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted last time worked for pay';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted last time worked for pay';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Sex';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Sex';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Ethnicity';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Ethnicity';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Education Attainment';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Education Attainment';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Region';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Region';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Disabilities';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Disabilities';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Disabilities (Vision)';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Disabilities (Vision)';
RUN;
title;
PROC FREQ data=final_variables;
TITLE 'Unweighted Disabilities (Hearing)';
RUN;
PROC SURVEYFREQ data=final_variables;
TITLE 'Weighted Disabilities (Hearing)';
RUN;
title;
DATA final_yueyan (KEEP = PPSU PSTRAT WTFA_A AGEP_A Sex Education Ethnicity Region_US Employed Workload Unemployed_time Disabilities Vision Hearing);
SET final_variables;
RUN;
PROC CONTENTS data=final_yueyan;
RUN;
** 19,781 obs and 14 variables;
DATA final.final_yueyan;
SET work.final_yueyan;
RUN;
* Table 2;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Education';
RUN;
title;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Disabilities';
RUN;
title;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Sex';
RUN;
title;
PROC SURVEYMEANS data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Age';
RUN;
title;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Ethnicity';
RUN;
title;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Region';
RUN;
title;
* Table 2.1;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Disabilities (Vision)';
RUN;
title;
PROC SURVEYFREQ data=final_yueyan;
TITLE 'Bivariate Analysis on Assocaition between Employed and Disabilities (Hearing)';
RUN;
title;
* Table 3;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Education (ref='1')/param=ref;
MODEL Employed (event='1')= education;
TITLE1 'Multivariate Analysis on Education and Employed';
TITLE2 'Ref group on Education: Less than high school';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Disabilities (ref='0')/param=ref;
MODEL Employed (event='1')= Disabilities;
TITLE1 'Multivariate Analysis on Education and Disabilities';
TITLE2 'Ref group on Disabilities: No disabilities';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Vision (ref='1')/param=ref;
MODEL Employed (event='1')= Vision;
TITLE1 'Multivariate Analysis on Education and Disabilities(Vision)';
TITLE2 'Ref group on Disabilities(Vision): No disability';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Hearing (ref='1')/param=ref;
MODEL Employed (event='1')= Hearing;
TITLE1 'Multivariate Analysis on Education and Disabilities(Hearing)';
TITLE2 'Ref group on Disabilities(Hearing): No disability';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Sex (ref='1')/param=ref;
MODEL Employed (event='1')= Sex;
TITLE1 'Multivariate Analysis on Education and Sex';
TITLE2 'Ref group on Sex: Male';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Ethnicity (ref='2')/param=ref;
MODEL Employed (event='1')= Ethnicity;
TITLE1 'Multivariate Analysis on Education and Ethnicity';
TITLE2 'Ref group on Ethnicity: Non-Hispanic White only';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Region_US (ref='3')/param=ref;
MODEL Employed (event='1')= Region_US;
TITLE1 'Multivariate Analysis on Education and Region';
TITLE2 'Ref group on Region: South';
RUN;
title;
PROC SURVEYLOGISTIC data=final_yueyan;
CLASS Education(ref='1') Sex(ref='1') Disabilities(ref='0') Vision(ref='1') Hearing(ref='1') Ethnicity(ref='2') Region_US(ref='3')/param=ref;
MODEL Employed (event='1')= Education Sex Disabilities Vision Hearing Ethnicity Region_US;
TITLE1 'Adjusted Multivariate Analysis on Education and Employed';
RUN;